### PR TITLE
Remove the Nation holding Colonists

### LINKED ISSUE #1828: NPE in the Colony code
**Describe the bug**
There is a NPE thrown in the Colony code when research projects are in play.

**Expected and unexpected behavior**
When the number of research projects change in a `Colony` a `Colonist` is removed from the `Population` and stored against the `Nation` pool.
The research project increase and the Colonist is reassigned back to the Colony but the Colonist is not assigned to a Colony. This will then generate a NPE on the next clock pulse.
The code clearly is wrong but it is unclear why this problem has not been uncovered previously.

**Discuss any potential problems you have and have not ruled out**
The solution is the `setColony` method must be applied when retrieving a Colonist from a Nation.
However the Colony logic does currently not impact the user's experience, it generates log but no visual representation nor does it have any indrect impact.
Therefore a flag will also be added to the Scenario concept that defines how many Colony are to be created. By default this will be zero.

### PR DESCRIPTION
**Pull request by bevans2000**
The Population class has a potential to generate random ClassCastException as it pulls Colonists from the Nation to be reused.

This removes the pooling of Colonists in the Nation class.

Close #1828

### CODE REVIEW

File: mars-sim-core/src/main/java/com/mars_sim/core/authority/Nation.java [hunk 1]
```diff
@@ -8,99 +8,26 @@
...
-	/**
-	 * Gross Domestic Product (GDP) is the standard measure of the value 
-	 * added created through the production of goods and services 
-	 * in a country during a certain period. 
-	 * 
-	 * As such, it also measures the income earned from that production, 
-	 * or the total amount spent on final goods and services 
-	 * (less imports).
-	 */
-	private double GDP;
```
Comment (mokun) [inline mars-sim-core/src/main/java/com/mars_sim/core/authority/Nation.java:44]: Can we have the GDP, PPP, annualGDPGrowth, GDPPerCapita, etc. back ?

Comment (mokun) [reply mars-sim-core/src/main/java/com/mars_sim/core/authority/Nation.java:44]: We will be loading these values from the xls/json file of that nation. They are considered useful params showcasing the economical capabilities of a nation.

Comment (bevans2000) [reply mars-sim-core/src/main/java/com/mars_sim/core/authority/Nation.java:44]: > Can we have the GDP, PPP, annualGDPGrowth, GDPPerCapita, etc. back ?

None of the values were used and just generated code smells. Add them back in once there is a use for them I think
