### PR TITLE
Reduce contention in Relationship logic

### LINKED ISSUE #893: ConcurrentModificationException in Relation's getAllKnownPeople() method
**Describe the bug**
- While putting together a set of known persons by thread 1, this set is potentially being visited/updated by thread 2. 
- The Person collection in UnitManager involved people from all settlements and thus from all threads.

**Expected and unexpected behavior**
- Will create a brand new set of persons with `new ArrayList<>()` help, since it involves 2 threads ?
- Q: what is the best strategy to avoid this ConcurrentModificationException ?

**Java classes involved**
- Relation, RelationshipUtil

**Stacktrace**
```
01-Adir-01:600.014 (Severe) UnitManager$SettlementTask : Problem with pulse on Tian Cheng: null
java.util.ConcurrentModificationException
	at java.base/java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1694)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at org.mars_sim.msp.core.person.ai.social.Relation.getAllKnownPeople(Relation.java:220)
	at org.mars_sim.msp.core.person.ai.social.RelationshipUtil.getAllKnownPeople(RelationshipUtil.java:165)
	at org.mars_sim.msp.core.person.ai.social.RelationshipUtil.getAverageOpinionOfMe(RelationshipUtil.java:219)
	at org.mars_sim.msp.core.person.ai.EmotionManager.checkStimulus(EmotionManager.java:129)
	at org.mars_sim.msp.core.person.ai.Mind.updateEmotion(Mind.java:551)
	at org.mars_sim.msp.core.person.ai.Mind.timePassing(Mind.java:128)
	at org.mars_sim.msp.core.person.Person.timePassing(Person.java:836)
	at org.mars_sim.msp.core.structure.Settlement.timePassingCitizens(Settlement.java:1086)
	at org.mars_sim.msp.core.structure.Settlement.timePassing(Settlement.java:923)
	at org.mars_sim.msp.core.UnitManager$SettlementTask.call(UnitManager.java:750)
	at org.mars_sim.msp.core.UnitManager$SettlementTask.call(UnitManager.java:1)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Specifications  (please complete the following information)**
 - pre 3.6.0 build 8083

**Additional context**
- How similar or disimilar is this concurrency situation compared to that of https://github.com/mars-sim/mars-sim/issues/883 ?

### PR DESCRIPTION
**Pull request by bevans2000**
This PR applies some improvements to the Person Relationship logic:

- The different attributes of a Relationship (e.g. trust etc) are modelled as a new Record called ```Opinion```. This replaces the generic Map and hence provides a more storage efficient representation.
- Relationships are only created one way now. When a Person forms an opinion of the other the reverse is not created because the other Person should form their own opinion. This removes a significant contention on the Relationship logic and means a Person is the only writer to their own Relation class

close #893

### CODE REVIEW

File: mars-sim-core/src/main/java/org/mars_sim/msp/core/person/ai/social/Relation.java [hunk 1]
```diff
@@ -21,18 +21,24 @@
  */
 public class Relation implements Serializable {
 
+	/**
+	 * Details of a specific relationship to a Person
+	 */
+	public record Opinion(double trust, double care, double respect) implements Serializable {
```
Comment (mokun) [inline mars-sim-core/src/main/java/org/mars_sim/msp/core/person/ai/social/Relation.java:27]: Great. We're now using record for the very first time in mars-sim.

I suppose when we switch to JSON serialization, record would be supported, right ?
